services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
  db:
    image: postgres:16
    env_file:
      - backend/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    env_file:
      - backend/.env
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"


  backend:
    build: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
    command:
      "pdm run start"
    profiles:
      - execution
      
  retriever:
    build: rag
    ports:
      - "8888:8888"
    depends_on:
      - qdrant
    command:
      "pdm run start"
    profiles:
      - execution

  setup_qdrant:
    build: rag
    depends_on:
      - qdrant
    command:
      "pdm run populate_exercises"
    profiles: 
      - setup
  
  setup_db:
    build: backend
    depends_on:
      - db
      - minio
    command:
      "bash ./setup.sh"
    profiles: 
      - setup

volumes:
  pg_data:
  minio_data:
  qdrant_storage:
